package com.pnf.OATPlugin;

import com.pnfsoftware.jeb.core.IUnitCreator;
import com.pnfsoftware.jeb.core.PluginInformation;
import com.pnfsoftware.jeb.core.input.IInput;
import com.pnfsoftware.jeb.core.properties.IPropertyDefinitionManager;
import com.pnfsoftware.jeb.core.units.AbstractUnitIdentifier;
import com.pnfsoftware.jeb.core.units.IUnit;
import com.pnfsoftware.jeb.core.units.IUnitProcessor;
import com.pnfsoftware.jeb.util.logging.GlobalLog;
import com.pnfsoftware.jeb.util.logging.ILogger;

public class OATPlugin extends AbstractUnitIdentifier {
    private static final ILogger logger = GlobalLog.getLogger(OATPlugin.class);

    static final String TYPE = "OAT";
    
    public OATPlugin() {
        super(TYPE, 0);
    }

    @Override
    public PluginInformation getPluginInformation() {
        return new PluginInformation(
                "OAT File Unit",
                "Plugin to extract dex files embedded in compiled OAT files that are generated by the ART",
                "1.0", "PNF Software");
    }

    @Override
    public void initialize(IPropertyDefinitionManager parent) {
        super.initialize(parent);
    }

    @Override
    public boolean canIdentify(IInput input, IUnitCreator parent) {
        return checkBytes(input, 0, (byte) 'o', (byte) 'a', (byte) 't',
                (byte) '\n');
    }

    @Override
    public IUnit prepare(String name, IInput input,
            IUnitProcessor unitProcessor, IUnitCreator parent) {
        OATUnit unit = new OATUnit(name, input, unitProcessor, parent, pdm);
        if (!unit.process()) {
            logger.info("Could not process unit %s", unit.getName());
        }
        return unit;
    }

}
